# Generated by Django 2.2.12 on 2020-06-22 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 18, 36, 16, 906885, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
