# Generated by Django 2.2.12 on 2020-06-22 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_auto_20200622_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 19, 1, 28, 779008, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
