# Generated by Django 2.2.12 on 2020-06-23 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20200623_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 45, 58, 926038, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
